USE [bus]
GO
CREATE PROCEDURE Add_Line
		@L_NAME NVARCHAR(50),  
		@L_ROUTE NVARCHAR(500) = '',  
		@L_START_TIME NCHAR(10),
		@L_END_TIME NCHAR(10),
		@L_PRICE NUMERIC(8, 2) = 0
	AS  
BEGIN
	IF EXISTS (
		SELECT * FROM [dbo].[bus]
		WHERE [name] = @L_NAME )
	RETURN 1;

	BEGIN TRY
	INSERT INTO [dbo].[bus] VALUES(
		@L_NAME, @L_ROUTE, @L_START_TIME, @L_END_TIME, @L_PRICE, DEFAULT
	);
	END TRY
	BEGIN CATCH
		RETURN 3;
	END CATCH	
	RETURN 2;
END
GO